ocadotechnology/codeforlife-package-javascript

lib/cjs/helpers/general.d.ts, lib/cjs/helpers/general.js, lib/esm/helpers/general.d.ts, lib/esm/helpers/general.js, src/helpers/general.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-javascript/4)
=> fix: added hello world helper

lib/cjs/helpers/general.d.ts, lib/cjs/helpers/general.js, lib/esm/helpers/general.d.ts, lib/esm/helpers/general.js, src/helpers/general.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-javascript/5)
=> fix: remove test helper

.github/workflows/javascript-package.yml, lib/cjs/helpers/general.d.ts, lib/cjs/helpers/general.js, lib/esm/helpers/general.d.ts, lib/esm/helpers/general.js, src/helpers/general.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-javascript/6)
=> fix: add test helper

lib/cjs/helpers/general.d.ts, lib/cjs/helpers/general.js, lib/esm/helpers/general.d.ts, lib/esm/helpers/general.js, src/helpers/general.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-javascript/7)
=> fix: remove helper

.github/workflows/main.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-javascript/10)
=> fix: just test

.github/workflows/main.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-javascript/11)
=> fix: pipeline

.github/workflows/main.yml, lib/cjs/helpers/general.d.ts, lib/cjs/helpers/general.js, lib/esm/helpers/general.d.ts, lib/esm/helpers/general.js, src/helpers/general.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-javascript/15)
=> fix: use action

lib/cjs/components/form/DateField.d.ts, lib/cjs/components/form/DateField.js, lib/cjs/components/form/SubmitButton.d.ts, lib/cjs/components/form/SubmitButton.js, lib/cjs/components/form/index.d.ts, lib/cjs/components/form/index.js, lib/cjs/helpers/formik.d.ts, lib/cjs/helpers/formik.js, lib/cjs/helpers/general.d.ts, lib/cjs/helpers/general.js, lib/esm/components/form/DateField.d.ts, lib/esm/components/form/DateField.js, lib/esm/components/form/SubmitButton.d.ts, lib/esm/components/form/SubmitButton.js, lib/esm/components/form/index.d.ts, lib/esm/components/form/index.js, lib/esm/helpers/formik.d.ts, lib/esm/helpers/formik.js, lib/esm/helpers/general.d.ts, lib/esm/helpers/general.js, src/components/form/DateField.tsx, src/components/form/SubmitButton.tsx, src/components/form/index.ts, src/helpers/formik.ts, src/helpers/general.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-javascript/21)
=> fix: home views

lib/cjs/components/page/Banner.js, lib/esm/components/page/Banner.js, src/components/page/Banner.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-javascript/19)
=> fix: new about us page edits

lib/cjs/components/page/Container.js, lib/esm/components/page/Container.js, src/components/page/Container.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-javascript/22)
=> feat: include notifications on page navigation

lib/cjs/theme/ThemedBox.d.ts, lib/cjs/theme/ThemedBox.js, lib/esm/theme/ThemedBox.d.ts, lib/esm/theme/ThemedBox.js, src/theme/ThemedBox.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-javascript/23)
=> fix: bgcolor

lib/cjs/components/form/DateField.js, lib/cjs/components/page/TabBar.js, lib/esm/components/form/DateField.js, lib/esm/components/page/TabBar.js, src/components/form/DateField.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-javascript/25)
=> fix: 84 modify datefield

lib/cjs/components/form/DateField.js, lib/esm/components/form/DateField.js, src/components/form/DateField.tsx
[Screencast from 31-08-23 11:29:06.webm](https://github.com/ocadotechnology/codeforlife-package-javascript/assets/65698922/6da243b1-98f6-4ce1-bae2-324d79bf9886)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-javascript/26)
=> fix: set maxHeight for register form select

src/components/form/CheckboxField.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-javascript/28)
=> fix: default checkbox value

lib/cjs/api/baseQuery.d.ts, lib/cjs/api/baseQuery.js, lib/cjs/api/index.d.ts, lib/cjs/api/index.js, lib/cjs/components/form/AutocompleteField.d.ts, lib/cjs/components/form/AutocompleteField.js, lib/cjs/components/page/Container.d.ts, lib/cjs/components/page/Container.js, lib/cjs/components/page/index.d.ts, lib/cjs/theme/components/MuiTabs.js, lib/esm/api/baseQuery.d.ts, lib/esm/api/baseQuery.js, lib/esm/api/index.d.ts, lib/esm/api/index.js, lib/esm/components/form/AutocompleteField.d.ts, lib/esm/components/form/AutocompleteField.js, lib/esm/components/page/Container.d.ts, lib/esm/components/page/Container.js, lib/esm/components/page/index.d.ts, lib/esm/theme/components/MuiTabs.js, src/api/baseQuery.ts, src/api/index.ts, src/components/form/AutocompleteField.tsx, src/components/page/Container.tsx, src/components/page/index.ts, src/theme/components/MuiTabs.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-javascript/29)
=> fix: select only autocomplete

.github/workflows/main.yml, lib/cjs/helpers/formik.d.ts, lib/cjs/helpers/formik.js, lib/esm/helpers/formik.d.ts, lib/esm/helpers/formik.js, src/helpers/formik.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-javascript/31)
=> fix: add is form error helper

lib/cjs/helpers/formik.d.ts, lib/cjs/helpers/jsCookie.d.ts, lib/cjs/helpers/jsCookie.js, lib/cjs/helpers/rtkQuery.d.ts, lib/cjs/helpers/rtkQuery.js, lib/cjs/hooks.d.ts, lib/cjs/hooks.js, lib/esm/helpers/formik.d.ts, lib/esm/helpers/jsCookie.d.ts, lib/esm/helpers/jsCookie.js, lib/esm/helpers/rtkQuery.d.ts, lib/esm/helpers/rtkQuery.js, lib/esm/hooks.d.ts, lib/esm/hooks.js, src/helpers/formik.ts, src/helpers/jsCookie.ts, src/helpers/rtkQuery.ts, src/hooks.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-javascript/33)
=> fix: foundation of breaking circular dependencies

.github/workflows/main.yml, CONTRIBUTING.md, LICENSE.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-javascript/35)
=> docs: license and contributing

.github/workflows/main.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-javascript/36)
=> ci: Replace Stefbot with CFLbot

.github/workflows/contributing.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-javascript/37)
=> Validate existing contributor

.devcontainer.json, .vscode/codeforlife.code-snippets, .vscode/settings.json, codeforlife.code-workspace
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-javascript/39)
=> add dev container

.vscode/launch.json, src/components/form/AutocompleteField.tsx, src/components/form/CheckboxField.tsx, src/components/form/DatePickerField.tsx, src/components/form/RepeatField.tsx, src/components/form/TextField.tsx, src/components/router/Link.tsx, src/components/router/LinkButton.tsx, src/components/router/LinkIconButton.tsx, src/components/router/LinkListItem.tsx, src/components/router/LinkTab.tsx, src/hooks/router.ts, src/utils/form.ts, src/utils/router.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-javascript/48)
=> fix: portal frontend#12

src/components/form/AutocompleteField.tsx, src/components/form/CheckboxField.tsx, src/components/form/RepeatField.tsx, src/components/form/TextField.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-javascript/62)
=> fix: id or name

src/theme/components/MuiTextField.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-javascript/63)
=> fix: add disabled state

src/api/models.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-javascript/68)
=> fix: Allow null requesting_to_join_class

.github/workflows/main.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-javascript/67)
=> fix: reuse release workflow

README.md, package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-javascript/71)
=> fix: remove peer dependencies

src/components/form/TextField.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-javascript/74)
=> fix: unique values

src/api/createApi.ts, src/utils/api.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-javascript/75)
=> fix: csrf header for non-safe http methods

src/components/form/Form.tsx, src/hooks/form.tsx, src/hooks/index.ts, src/utils/form.test.ts, src/utils/form.ts, src/utils/general.test.ts, src/utils/general.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-javascript/77)
=> fix: Package javascript 76

src/components/form/Form.tsx, src/components/form/SubmitButton.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-javascript/79)
=> fix: form submission behavior

package.json, src/settings/index.ts, src/vite.config.ts, vite.config.ts, yarn.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-javascript/82)
=> fix: Portal frontend 48

package.json, yarn.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-javascript/84)
=> fix: Upgrade to Node 22

.eslintrc.json, .github/workflows/main.yml, yarn.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-package-javascript/86)
=> fix: Node 22
